version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    env_file:
      - ./frontend/.env.dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      CONFIG_FILE_PATH: "/app/config.dev.json"
      SERVER_PORT: "8080"
      DB_USER: "root"
      DB_PASSWORD: "root"
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_schema
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - my_network

networks:
  my_network:
    external: false
